export const FILTERS_SET_PARTY_ITEM = 'SET_PARTY_ITEM'
export const FILTERS_ADD_PARTY_ITEM = 'ADD_PARTY_ITEM'
export const FILTERS_DELETE_PARTY_ITEM = 'DELETE_PARTY_ITEM'
export const FILTERS_SET_ENVIRONMENT = 'SET_ENVIRONMENT'
export const FILTERS_SET_MONSTER_TYPE = 'SET_MONSTER_TYPE'
export const FILTERS_SET_SETTINGS = 'SET_SETTINGS'

export const MONSTERS_SET_FILTER = 'SET_FILTER'
